### ISSUE TITLE
Windows download file out-of-memory

### ISSUE THREAD

**Issue by Kxnrl** [dordnung/System2#15]
game: csgo
Platform: windows

I try download big file, but csgo srcds is 32bit app, will instantly crash server

Is this problem?
https://github.com/dordnung/System2/blob/6b15e6931373a37f828626848441b031ae6c27b2/threads/RequestThread.cpp#L127

**Comment by dordnung** [comment]
Hey,
thanks for finding this, it will be fixed with the next update
