### ISSUE TITLE
Does not load on Insurgency or CSS servers. Works perfectly fine on tf2 servers.

### ISSUE THREAD

**Issue by Synkstar** [dordnung/System2#19]
[09] <FAILED> file "system2.ext.so": /home/container/bin/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/container/insurgency/addons/sourcemod/extensions/system2.ext.so)

I am running pterodactyl and the servers are on the same machine using the same docker image. I have no clue how to fix this.

**Comment by kaju666** [comment]
have the same error

**Comment by kaju666** [comment]
I tested and latest version without this error in CSS is 3.2.1

**Comment by kaju666** [comment]
I solved this (or found a solution on allied mods) :)
just copy libstdc++.so.6 from /lib and copy to /bin of your server

https://forums.alliedmods.net/showpost.php?p=2766522&postcount=126

latest version works!

**Comment by Synkstar** [comment]
I ended up switching that script to use steamworks instead because this plugin is rather outdated and I only needed to do http requests. It was a much cleaner looking solution too.
