### ISSUE TITLE
Anti-virus detects viruses every time I download

### ISSUE THREAD

**Issue by crashzk** [dordnung/System2#20]
Whenever I go to download the latest version I am blocked by the anti-virus protection saying that the download was blocked due to malware.

![image](https://user-images.githubusercontent.com/32937653/213192287-ca0ca0d0-1ddb-4776-9c2c-1e89f16bf4d2.png)

**Comment by crashzk** [comment]
Even if I completely disable the antivirus, the browser itself blocks the download.

![image](https://user-images.githubusercontent.com/32937653/213242391-a097e17b-28f3-4f33-8afc-ac3c2143705f.png)

**Comment by freakexeuLow** [comment]
@crashzk try it with a different web browser..i .downloaded it normally with opera without being blocked

**Comment by crashzk** [comment]
Had tested in other browsers, same problem. I tested it on Opera GX now, it was, it downloaded everything right.

I believe it was something temporary, my network something like that.

Anyway, thank you
