### ISSUE TITLE
GET request doesn't work when installed on Fedora, "error setting certificate verify locations"

### ISSUE THREAD

**Issue by iluno90** [dordnung/System2#7]
On a fresh install on Fedora 29, I am unable to get an HTTP(s) GET request to work with my script, I get the following error when trying to request an https page:

     Failure - error setting certificate verify locations:   CAfile: /etc/ssl/certs/ca-certificates.crt   CApath: none

I checked and I have "ca-certificates" package installed; I also don't get any errors when using my system's version of curl in cli, eg, 'curl https://url.tld' always works fine and shows the source code, it's only on System2 that I seem to have the problem.

I installed System2 from the .zip on the sourcemod forums. I found another reference to this error on the sourcemod forums from someone with CentOS (similar to Fedora)

/etc/ssl/certs has the following files on my system:

    ca-bundle.crt  ca-bundle.trust.crt  postfix.pem

**Comment by iluno90** [comment]
If I make a symlink in /etc/ssl/certs called ca-certifcates.crt that points to ca-bundle.crt, it works. I think the problem is that somewhere it's hardcoded to use ca-certificates.crt which doesn't seem to be the correct name/location on some OS's

**Comment by dordnung** [comment]
Thanks for the report. I'll take a look at it

**Comment by iluno90** [comment]
Yes that fixes it and it works now on Fedora :)

**Comment by dordnung** [comment]
Alright, thanks for letting me know
