### ISSUE TITLE
Problem using compression options

### ISSUE THREAD

**Issue by nanociaglia** [dordnung/System2#9]
I'm using a plugin that automatically uploads a demo from a gameserver to a webserver (similar as tAutoDemoUpload plugin) but there're some errors using system2 like this:

`Error uploading demo demos/testing1.dem (Uploaded unaligned file size (75086725 out of 75083776 bytes))`

`Error uploading demo demos/testing2.bz2 (Can not open file to upload)`

And sometimes it compress the demos but they're too small (22 bytes and there's nothing inside the packed file)

https://i.imgur.com/lUbTJg3.png

I've added you in steam friends so we can talk better there

**Comment by PhlexPlexico** [comment]
It seems that I'm having the same issue when trying to upload a raw demo with FTP.
`There was a problem: Uploaded unaligned file size (624559 out of 565248 bytes)`

**Comment by PhlexPlexico** [comment]
Could it by chance be how the file size is determined for uploading files? [For example](https://github.com/dordnung/System2/blob/2c3b1dfd31bf9eaede9ba7812b4b2819c8d43933/threads/FTPRequestThread.cpp#L86)

I haven't done any work with libcurl, but could it be somehow getting the filesize incorrectly and then sending it?

**Comment by nanociaglia** [comment]
This error still happening, any idea?

**Comment by dordnung** [comment]
Sorry I didn't had time for it. Could you send me a file which fails for you?

**Comment by nanociaglia** [comment]
Add me on discord nano#7638 or steam https://steamcommunity.com/id/nano2k06/
I'll give you everything to you

**Comment by dordnung** [comment]
I really tried to reconstruct the problem, but it never appeared.
Maybe this was a libcurl problem and is now fixed. So please try the newest system2 version (3.3.0).

If it still not works it would really help, if you give me a file, which won't work for you
